AquaSettledText_OrbBeganGlowing: @ 81B4F03
	.string "{PLAYER}'s BLUE ORB suddenly began\n"
	.string "glowing!$"

AquaSettledText_KyogreSettledIntoSleep: @ 81B4F29
	.string "KYOGRE appears to have settled\n"
	.string "into sleep again...$"

AquaSettledText_ArchieThis: @ 81B4F5C
	.string "ARCHIE: This...$"

AquaSettledText_ArchieGoodbye: @ 81B4F6C
	.string "ARCHIE: ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "This is good-bye.\n"
	.string "This is the last you've seen of me...$"
